baseURL = 'https://joao-lobo-fernandes.github.io/'
languageCode = 'en-us'
title = 'João Lobo Fernandes'
theme = "lobo-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)']]

[menu]

[params]
    author = "João Lobo Fernandes"

[caches]
  [caches.images]
    dir = ':cacheDir/images'